### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by arzam16** [cyrozap/mediatek-lte-baseband-re#9]
What license the code is under? I'd like to use some great work from `SoC/common/` in my projects but I haven't found a license.

**Comment by arzam16** [comment]
@cyrozap ping 👋

**Comment by cyrozap** [comment]
I'm very sorry for how long it took me to do this, but with commit 48466dbc730c7d345da9adc379efa9f9bcdff079 I've finally added proper licenses to all the code in this repository.

Please see the individual files for license details as they are not all under the same license.
